# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Master branch mvn test

on:
  push:
    branches: [ elias-branch ]
  pull_request:
    branches: [ elias-branch ]
  create:
    branches: [ elias-branch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Test with Maven
      run: mvn clean test
